/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package u24739163_northwind_gui;
import java.sql.*;
import java.io.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
// sqlj.runtime.*;
/**
 *
 * @author makha
 */
public class northwind_GUI extends javax.swing.JFrame {

    /**
     * Creates new form northwind_GUI
     */
    public northwind_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void loadData(String filter) {
        try {
            // TODO code application logic here
            Class.forName("org.mariadb.jdbc.Driver");
            System.out.println("Driver loaded successfully");
            
                Connection con = DriverManager.getConnection("jdbc:mariadb://localhost:3306/u24739163_northwind", "root", "4659");
                System.out.println("Database connected");
                
                Statement st = con.createStatement();
                String sqlText;
                sqlText = "SELECT e.id, e.first_name, e.last_name, e.address, '' AS address_line_2, e.city, e.country_region, e.zip_postal_code, e.business_phone, e.company, " 
                    + "CASE WHEN EXISTS (" 
                    + "SELECT 1 FROM orders o " 
                    + "WHERE o.employee_id = e.id) " 
                    + "THEN 'Active' " 
                    + "ELSE 'Inactive' " 
                    + "END AS employment_status " 
                    + "FROM employees e " 
                    + "ORDER BY e.id";
                
                // Nests the sql query and filters out the filtered tuples based on the filtered word
                if(filter != null) {
                    sqlText = "SELECT * FROM (" + sqlText + ") e "
                            + "WHERE LOWER(e.first_name) LIKE LOWER(\'" + filter + "%\')";
                }
                System.out.println(sqlText);
                st.execute(sqlText);
                DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "First Name", "Last Name", "Address", "Address Line 2", "City", "Region", "Postal Code", "Phone", "Office", "Active"}, 0);
                jTableEmployees.setModel(model);
                ResultSet rs = st.executeQuery(sqlText);
                String i, f, l, a, a2, c, r, pc, p, o, ac;
                while(rs.next()) {
                    i = rs.getString("e.id");
                    f = rs.getString("e.first_name");
                    l = rs.getString("e.last_name");
                    a = rs.getString("e.address");
                    a2 = rs.getString("address_line_2");
                    c = rs.getString("e.city");
                    r = rs.getString("e.country_region");
                    pc = rs.getString("e.zip_postal_code");
                    p = rs.getString("e.business_phone");
                    o = rs.getString("e.company");
                    ac = rs.getString("employment_status");
                    model.addRow(new Object[]{i, f, l, a, a2, c, r, pc, p, o, ac});
                }
        } catch (ClassNotFoundException ex) {
            System.out.println("ex" + ex);
        } catch (SQLException ex) {
            System.out.println("ex" + ex);
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedNorthwindGUI = new javax.swing.JTabbedPane();
        jPanelEmployees = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployees = new javax.swing.JTable();
        lblFilter = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jPanelProducts = new javax.swing.JPanel();
        btnAddProductData = new javax.swing.JButton();
        jPanelReports = new javax.swing.JPanel();
        jPanelNotifications = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Address", "Address line 2", "City", "Region", "Postal code", "Phone", "Office", "Active"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmployees);

        lblFilter.setText("Filter by name: ");

        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmployeesLayout = new javax.swing.GroupLayout(jPanelEmployees);
        jPanelEmployees.setLayout(jPanelEmployeesLayout);
        jPanelEmployeesLayout.setHorizontalGroup(
            jPanelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmployeesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelEmployeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEmployeesLayout.setVerticalGroup(
            jPanelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilter)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedNorthwindGUI.addTab("Employees", jPanelEmployees);

        btnAddProductData.setText("Add Product");
        btnAddProductData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductsLayout = new javax.swing.GroupLayout(jPanelProducts);
        jPanelProducts.setLayout(jPanelProductsLayout);
        jPanelProductsLayout.setHorizontalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnAddProductData)
                .addContainerGap(784, Short.MAX_VALUE))
        );
        jPanelProductsLayout.setVerticalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductsLayout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(btnAddProductData)
                .addContainerGap())
        );

        jTabbedNorthwindGUI.addTab("Products", jPanelProducts);

        javax.swing.GroupLayout jPanelReportsLayout = new javax.swing.GroupLayout(jPanelReports);
        jPanelReports.setLayout(jPanelReportsLayout);
        jPanelReportsLayout.setHorizontalGroup(
            jPanelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        jPanelReportsLayout.setVerticalGroup(
            jPanelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedNorthwindGUI.addTab("Reports", jPanelReports);

        javax.swing.GroupLayout jPanelNotificationsLayout = new javax.swing.GroupLayout(jPanelNotifications);
        jPanelNotifications.setLayout(jPanelNotificationsLayout);
        jPanelNotificationsLayout.setHorizontalGroup(
            jPanelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        jPanelNotificationsLayout.setVerticalGroup(
            jPanelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedNorthwindGUI.addTab("Notifications", jPanelNotifications);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedNorthwindGUI)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedNorthwindGUI)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        // TODO add your handling code here:
        if(txtFilter.getText() != null) {
            loadData(txtFilter.getText());
        }
    }//GEN-LAST:event_txtFilterActionPerformed

    private void btnAddProductDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductDataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddProductDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(northwind_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(northwind_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(northwind_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(northwind_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProductData;
    private javax.swing.JPanel jPanelEmployees;
    private javax.swing.JPanel jPanelNotifications;
    private javax.swing.JPanel jPanelProducts;
    private javax.swing.JPanel jPanelReports;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedNorthwindGUI;
    private javax.swing.JTable jTableEmployees;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
